default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.1
    hooks:
    - id: isort
      entry: isort --settings-path setup.cfg
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      entry: black --config pyproject.toml
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
    - id: flake8
      name: flake8
      entry: flake8 --config=setup.cfg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    - id: mypy
      name: mypy
      entry: mypy --config-file setup.cfg

