default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      entry: isort --settings-path setup.cfg
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
      entry: black --config pyproject.toml
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
    - id: flake8
      name: flake8
      entry: flake8 --config=setup.cfg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    - id: mypy
      name: mypy
      entry: mypy --config-file setup.cfg
      additional_dependencies:
        - types-requests
      language_version: python3.10